// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoomBooking.Persistance;

#nullable disable

namespace RoomBooking.Persistance.Migrations
{
    [DbContext(typeof(RoomBookingAppDbContext))]
    partial class RoomBookingAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("RoomBooking.Domain.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Conference Room A"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Conference Room B"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Conference Room C"
                        });
                });

            modelBuilder.Entity("RoomBooking.Domain.RoomBookingData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("RoomID");

                    b.ToTable("RoomBookings");
                });

            modelBuilder.Entity("RoomBooking.Domain.RoomBookingData", b =>
                {
                    b.HasOne("RoomBooking.Domain.Room", "Room")
                        .WithMany("RoomBokings")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");
                });

            modelBuilder.Entity("RoomBooking.Domain.Room", b =>
                {
                    b.Navigation("RoomBokings");
                });
#pragma warning restore 612, 618
        }
    }
}
